import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Built from the folders in docs/; order pages with `sidebar_position` and folders with _category_.json.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
